M48
; DRILL file {KiCad (6.0.9)} date Mon Jan  2 08:45:51 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-02T08:45:51+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X156.8Y-97.66
X156.8Y-100.2
X156.8Y-102.74
X166.0Y-97.66
X166.0Y-100.2
X166.0Y-102.74
T2
X161.4Y-92.2
X161.4Y-108.2
T0
M30
